name: CI for static site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -l

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Validate HTML
        run: htmlhint "**/*.html"
