name: CI for static site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -l

      - name: Run W3C HTML Validator
        uses: Cyb3r-Jak3/w3c-validation-action@v1
        with:
          directory: .
