name: CI for static site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -l

      - name: Validate HTML
        uses: CycJimmy/html-validator-action@v1
        with:
          html_path: ./index.html
