name: CI Test Workflow

on:
  push:
    branches: [ main ]   # Runs whenever you push to main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in repo
      run: ls -R
